/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testtabla.BebidasDialogs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import testtabla.ConexionBD;
import testtabla.Models.BebidaModel;

/**
 *
 * @author Ghost
 */
public class ModificarBebidaDialog extends javax.swing.JDialog {
    
    Connection conn = ConexionBD.getInstance().getConnection();
    
    private BebidaModel bebida;
    private Boolean cambio;

    /**
     * Creates new form ModificarEventoDialog
     */
    public ModificarBebidaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cambio = false;
    }
    
    public ModificarBebidaDialog(java.awt.Frame parent, boolean modal, BebidaModel nbebida) {
        super(parent, modal);
        initComponents();
        
        bebida = nbebida;
        
        int id = bebida.getId();
        
        labelId.setText(String.valueOf(id));
        txtNombre.setText(bebida.getNombre());
        cboxDenominacion.setSelectedIndex(bebida.getDenominacion());
        checkDisponible.setSelected(bebida.getDisponible());
      
        cambio = false;
    }
    
    public void setId(int id){
        this.bebida.setId(id);
    }
    
    public void setNombre(String nombre){
        this.bebida.setNombre(nombre);
    }
    
    public void setDenominacion(int denominacion){
        this.bebida.setDenominacion(denominacion);
    }
    
    public void setDisponible(Boolean disponible){
        this.bebida.setDisponible(disponible);
    }
    
    public int getId(){
        return this.bebida.getId();
    }
    
    public String getNombre(){
        return this.bebida.getNombre();
    }
    
    public int getDenominacion(){
        return this.bebida.getDenominacion();
    }
    
    public Boolean getDisponible(){
        return this.bebida.getDisponible();
    }
    
    public Boolean getCambio(){
        return cambio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        checkDisponible = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboxDenominacion = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Evento");

        jLabel1.setText("Id:");

        jLabel2.setText("Nombre:");

        labelId.setText("jLabel4");

        checkDisponible.setText("Disponible");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Denominación:");

        cboxDenominacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mililitros", "Medio litros", "Litros", "Dos litros", "Tres litros" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(42, 42, 42)
                .addComponent(btnCancelar)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboxDenominacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(checkDisponible)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(checkDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.bebida.setNombre(txtNombre.getText());
        this.bebida.setDenominacion(cboxDenominacion.getSelectedIndex() + 1);
        this.bebida.setDisponible(checkDisponible.isSelected());
        modificarBebida(this.bebida);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    private void modificarBebida(BebidaModel bebida){
        //int id = evento.getId();
		
		//Modificar el evento
		try {
                            String queryModificarPro = "UPDATE bebidas SET nombre = ? , denominacion = ?, registro_disponible = ? WHERE id_bebida = ?";

			PreparedStatement execQuery = conn.prepareStatement(queryModificarPro);
			execQuery.setString(1, bebida.getNombre());
                        execQuery.setInt(2, bebida.getDenominacion());
			execQuery.setBoolean(3, bebida.getDisponible());
			execQuery.setInt(4, bebida.getId());

			execQuery.executeUpdate();

			//Mostrar mensaje
			JOptionPane.showMessageDialog(null, "Bebida ha sido modificada.");
                        
                        this.cambio = true;
		} catch (SQLException errorMod) {
			JOptionPane.showMessageDialog(null, "Error al modificar la bebida. \n" + errorMod, "Error", JOptionPane.ERROR_MESSAGE);
		}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarBebidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarBebidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarBebidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarBebidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarBebidaDialog dialog = new ModificarBebidaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cboxDenominacion;
    private javax.swing.JCheckBox checkDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
